### ISSUE TITLE
请求增加封装base64编码直接转换成配置文件

### ISSUE THREAD

**Issue by erge6521** [changfeng2021/cf-clash#1]
如题，请求增加一个base64编码直接转换成订阅链接或者配置文件的功能，这样的话测速过的服务器就可以直接添加了

**Comment by changfeng2021** [comment]
这个功能在 `https://v2rayse.com` 里面已经有了，那里面很强大，可以自己编辑模版、选择 `acl4ssr`模版等功能，我也不想在2个地方维护转换功能。
以后可能会在这里加一个基本的转换功能
