### ISSUE TITLE
level=error msg="[IPTABLES]

### ISSUE THREAD

**Issue by hu-lielie** [changfeng2021/cf-clash#13]
在长风clash界面应用配置，然后报错：
time="2023-03-19T14:03:21Z" level=error msg="[IPTABLES] setting iptables failed: DNS server must be correct"

setting iptables failed: DNS server must be correct这个是什么问题

**Comment by hu-lielie** [comment]
我是在Mac上装的parallels，桥接的虚拟机Ubuntu 22.04，在里面使用docker，但是无法代理

**Comment by tigerwoo** [comment]
debian,Docker.同样的错误.

**Comment by tigerwoo** [comment]
试着修改了一下配置文件中有关DNS设置部分,全部删除就ok了.@hu-lielie

**Comment by hu-lielie** [comment]
厉害哥们
